/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.rahulsom.changeloglint

import org.gradle.api.Plugin
import org.gradle.api.Project

class ChangelogLintPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        project.extensions.create("changelogLint", ChangelogLintExtension::class.java)
        project.tasks.create("changelogLint", ChangelogLintTask::class.java)
    }
}
